### ISSUE TITLE
Error: Cannot resolve type entity i9.PortalModule to symbol

### ISSUE THREAD

**Issue by hamzasgh** [ng-ghost-rider/ghost-rider#28]
i added all the code as the readmfile but im keep getting **Error: Cannot resolve type entity i9.PortalModule to symbol** and when my project is launched i get **Failed to load resource: the server responded with a status of 404 (Not Found)** any help please?

**Comment by freddysilber** [comment]
Hey @hamzasgh ! Thanks for the feedback. Do you have any screenshots and/or possibly a link to the source code so I could look into this? What Angular version are you on?
